### ISSUE TITLE
PIL.UnidentifiedImageError

### ISSUE THREAD

**Issue by Towhid1** [gribbg/pillow_svg#5]
```python
import pillow_svg.SvgImagePlugin
from PIL import Image

file = "image_emb/sample_640×426.svg"
svg_image = Image.open(file)
svg_image.show()
```

got error :
```sh
Traceback (most recent call last):
  File ".\pilsvg.py", line 5, in <module>
    svg_image = Image.open(file)
  File "D:\Client\venv\lib\site-packages\PIL\Image.py", line 3030, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'image_emb/sample_640×426.svg'
```

**Comment by nandoflorestan** [comment]
I did the same thing, got the same error, but I am attaching my SVG file so someone can reproduce the problem.
![test](https://github.com/gribbg/pillow_svg/assets/543841/318edbea-7ab1-4171-8fdc-95e2a931276d)
